version: "3"

services:
  fdv_win_fed_37_s:
    environment:
        - FDV_GIT_REPO
        - FDV_GIT_BRANCH
        - FDV_CLEAN
        - FDV_CMAKE
        - FDV_BOOTSTRAP_WX
    build: 
      context: fdv_win_fedora
      args:
         - FED_REL=37

    image:  fdv_win_fed37_i
    container_name: 'fdv_win_fed37_c'
    volumes:
            - win_fed37_v:/home/build/

volumes:
  win_fed37_v:
